<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="CopyRequiredFiles" BeforeTargets="BeforeBuild">
		<ItemGroup>
			<SourceTSFile Include="$(MSBuildThisFileDirectory)..\requiredFiles\IClassBringer.d.ts" />
		</ItemGroup>

		<Message Importance="high" Text="[Blazura] Copying file: @(SourceTSFile) to $(MSBuildProjectDirectory)\Scripts\IClassBringer.d.ts" />
		<Copy
		  SourceFiles="@(SourceTSFile)"
		  DestinationFiles="$(MSBuildProjectDirectory)\Scripts\IClassBringer.d.ts"
		  SkipUnchangedFiles="false" />

		<Message Importance="high" Text="[Blazura] Copying file: $(MSBuildThisFileDirectory)..\requiredFiles\ClassBringer.d.ts.copy to $(MSBuildProjectDirectory)\Scripts\ClassBringer.d.ts" />
		<Copy
		  SourceFiles="$(MSBuildThisFileDirectory)..\requiredFiles\ClassBringer.d.ts.copy"
		  DestinationFiles="$(MSBuildProjectDirectory)\Scripts\ClassBringer.d.ts"
		  SkipUnchangedFiles="false" />

		<Message Importance="high" Text="[Blazura] Copying file: $(MSBuildThisFileDirectory)..\requiredFiles\Root.scss to $(MSBuildProjectDirectory)\Styles\Root.scss" />
		<Copy
		  SourceFiles="$(MSBuildThisFileDirectory)..\requiredFiles\Root.scss"
		  DestinationFiles="$(MSBuildProjectDirectory)\Styles\Root.scss"
		  SkipUnchangedFiles="false" />

		<Message Importance="high" Text="[Blazura] Copying file: $(MSBuildThisFileDirectory)..\requiredFiles\tsconfig.json to $(MSBuildProjectDirectory)\tsconfig.json" />
		<Copy
		  SourceFiles="$(MSBuildThisFileDirectory)..\requiredFiles\tsconfig.json"
		  DestinationFiles="$(MSBuildProjectDirectory)\tsconfig.json"
		  SkipUnchangedFiles="false" />
	</Target>
</Project>
