name: Deploy Documentation Website

permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build_docs.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ vars.IMAGE_NAME }}-image
          path: .
          pattern: ${{ vars.IMAGE_NAME }}.tar

      - name: SCP into the server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./${{ vars.IMAGE_NAME }}.tar"
          target: "~/"

      - name: Start deployment
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker load -i ${{ vars.IMAGE_NAME }}.tar &&
            rm ${{ vars.IMAGE_NAME }}.tar &&
            grim up ${{ vars.IMAGE_NAME }} &&
            docker system prune -af
