name: Deploy Documentation Website

# TODO: Run this on publishing a new version of the package once deployment has been implemented
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/build_docs.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ vars.IMAGE_NAME }}-image
          path: .
          pattern: ${{ vars.IMAGE_NAME }}.tar

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v6
        with:
          name: ${{ vars.IMAGE_NAME }}-image

      - name: SCP into the server
        uses: appleboy/scp-action@6dba043acb2fa9973346e5025373dd76f2a50779 # master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./${{ vars.IMAGE_NAME }}.tar"
          target: "~/"

      - name: Start deployment
        uses: appleboy/ssh-action@068c0c7a4e59a5ae12fb7cb454b05735d830c82b # master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker load -i ${{ vars.IMAGE_NAME }}.tar &&
            rm ${{ vars.IMAGE_NAME }}.tar &&
            grim up ${{ vars.IMAGE_NAME }} &&
            docker system prune -af
